### ISSUE TITLE
internal links point to middle of div instead of start

### ISSUE THREAD

**Issue by mslgam** [wkhtmltopdf/wkhtmltopdf#1947]
I'm running wkhtmltopdf on Linux (Ubuntu Precise) 64-bit, version 0.12.1. I have a simple HTML file where most text is enclosed in a div, and following that, I have a link to the div. In the generated PDF, clicking on the link sends me to the middle of the div instead of the top. I've pasted a short HTML file below that has the problem. FYI, to get a working version, replace the line
`<p><strong>Top of div</strong></p>`
with
`<p><strong>Top of div</strong></p></div><div>`

``` HTML
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=us-ascii">
<meta http-equiv="Content-Style-Type" content="text/css">
</head>
<body>
<div id="section_2.1.4" class="section">
<p><strong>Top of div</strong></p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
<p>paragraph</p>
</div>
<a href="#section_2.1.4">Link to top</a>
</body>
</html>
```

**Comment by stas00** [comment]
I have a related problem. When compiling together several html files - if files link to each other directly as in file2.html has <a href="file1.html">blah</a> in it - the internal pdf link ends up one page too many, which is very odd as the links from TOC work correctly. Same example as given by the original poster by make 2 files and crosslink between the two. Thank you. Using 0.12.2.1 (with patched qt).

**Comment by ashkulz** [comment]
I think this Qt patch might be enough to fix this bug:
```diff
diff --git a/src/3rdparty/webkit/Source/WebKit/qt/Api/qwebframe.cpp b/src/3rdparty/webkit/Source/WebKit/qt/Api/qwebframe.cpp
index 053e393b3f..9331fb6f3c 100644
--- a/src/3rdparty/webkit/Source/WebKit/qt/Api/qwebframe.cpp
+++ b/src/3rdparty/webkit/Source/WebKit/qt/Api/qwebframe.cpp
@@ -297,7 +297,7 @@ QPair<int, QRectF> QWebPrinter::elementLocation(const QWebElement & e)
 
     int low=0;
     int high=pageRects.size();
-    int c = r.y() + r.height() / 2;
+    int c = r.y();
     while(low <= high) {
         int m = (low+high)/2;
         if(c < pageRects[m].y())
```
Need to investigate this, though.

**Comment by mattemoore** [comment]
What version was this fixed in?

**Comment by ashkulz** [comment]
@mattemoore: if you can confirm if the patch above fixes the issue, that'd be great :+1:

**Comment by mattemoore** [comment]
@ashkulz If I'm running DocFX (thus wkhtmltopdf) on Windows I need to build using the Vagrant/Virtualbox build environment yes?

**Comment by florian72810** [comment]
@ashkulz: I was having the same problem. I just tested the Qt patch on Ubuntu 18.04 and I confirm it fixes the issue.

 You can check the patched version here:
- amd64: https://flogg.fr/wp-content/uploads/2019/09/wkhtmltox_0.12.6-0.20190712.20.dev.e3fa5a9.bionic_amd64.deb
- i386: https://flogg.fr/wp-content/uploads/2019/09/wkhtmltox_0.12.6-0.20190712.20.dev.e3fa5a9.bionic_i386.deb

**Comment by adamgit** [comment]
So ... opened in 2014, patched 5 years later, but 8 years later it's still broken in all available releases?

Is the only way to get this working: setup the full build pipeline (with the proprietary packaging setup), apply the patch, and rebuild from source?

As per @icnocop 's mention (3 years ago): this affects anyone (everyone?) using Microsoft's only available versions of docFX (which is itself the only way to generate docs for C#).
