### ISSUE TITLE
Line break in Mathjax not working

### ISSUE THREAD

**Issue by arjunsuresh** [wkhtmltopdf/wkhtmltopdf#3684]
Thank you for the wonderful tool. I'm using "\\" for adding a newline character inside Mathjax which works fine on chrome and firefox. But using wkhtmltopdf when I generate the PDF, this newline is missing. Also, when the Mathjax equation becomes too large, there is no newline character added and the content gets clipped. I tried on 12.4 and 13.0-alpha

**Comment by Tomsgu** [comment]
Is this fixed in 0.12.5? If not, can you post a minimal test example so we can reproduce the issue?

**Comment by arjunsuresh** [comment]
The following HTML code actually reproduces this issue even on 0.12.6

```<html>
<head>
          <meta http-equiv="content-type" content="text/html;charset=utf-8">

<script  type="text/x-mathjax-config">  MathJax.Hub.Config({
    tex2jax: {
      inlineMath: [ ['$','$'], ["\\(","\\)"] ],
     config: ["MMLorHTML.js"],
      jax: ["input/TeX"],
      processEscapes: true
    },
  });

MathJax.Hub.Config({
"HTML-CSS": {
linebreaks: { automatic:true},
},
  });


</script><script  async type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

</head>
<body>
        <p> Hi $x^2\\p=0$</p>
</body>
</html>```

And this line `linebreaks: { automatic:true},` is the culprit :)

**Comment by PhilterPaper** [comment]
You have a number of tickets open regarding MathJax. I presume this is a Javascript-based package? If so, you need to be aware that wkHTMLtoPDF uses WebKit to process the page (including Javascript), and it has rather old capabilities. Many modern JS packages have problems with wkHTMLtoPDF, because they are relying on "modern" (i.e., less than 5-10 or so years old) JS features that WebKit lacks. Sometimes there may be workarounds for a problem, by changing the MathJax code, but other times you may be stuck.

Be aware that a number of browsers (Chrome and perhaps Firefox among them) can directly export as PDF. The results may or may not be what you desire, but it's worth a try.

**Comment by arjunsuresh** [comment]
Thank you Phil for your suggestion. Is there a way to get wkhtmltopdf to use modern browser engine or is that completely out of scope? We have tried Chrome and though it does render everything well our requirement to make a PDF book out of it is still not possible. The below PDF is made using wkhtmltopdf and we had to go through many work arounds. If there are some steps to be done to modernise wkhtmltopdf we are happy to contribute as its a tool worth continuing. 

https://github.com/GATEOverflow/GO-PDFs/blob/main/Volume-1.pdf

**Comment by PhilterPaper** [comment]
I haven't tried it myself, but I understand that some people report that they have successfully _built_ wkHTMLtoPDF to use the latest Chrome rendering engine, resulting in up-to-date Javascript and CSS support. It would be wonderful for the basic wkHTMLtoPDF to be rebuilt to use this, but I just don't see any progress on this front from the owner. Maybe you can try searching the tickets for "Chrome" or "headless" and see what you can find.
